[workspace]
members = ["machi", "machi-cli", "machi-derive"]
default-members = ["machi"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pyroth/machi"

[workspace.dependencies]
# A-F
anyhow = "1.0"
as-any = "0.3"
assert_fs = "1.1"
async-stream = "0.3"
base64 = "0.22"
bytes = "1.10"
convert_case = "0.10"
deluxe = { version = "0.5", features = ["full"] }
epub = "2.1"
eventsource-stream = "0.2"
fastrand = "2.3"
futures = "0.3"
futures-timer = "3.0"
glob = "0.3"

# H-M
http = "1.3"
indoc = "2.0"
lopdf = "0.39"
machi = { path = "machi" }
machi-derive = { path = "machi-derive" }
mime = "0.3"
mime_guess = "2.0"

# O-R
ordered-float = "5.1"
pin-project-lite = "0.2"
proc-macro2 = { version = "1.0", features = ["proc-macro"] }
quick-xml = "0.39"
quote = "1.0"
rayon = "1.10"
reqwest = { version = "0.13", features = ["json", "stream", "multipart"] }
reqwest-middleware = { version = "0.5", features = ["json", "multipart", "charset", "http2"] }
rmcp = { version = "0.14", features = ["client"] }

# S
schemars = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_path_to_error = "0.1"
serenity = "0.12"
syn = { version = "2.0", features = ["full"] }

# T-Z
thiserror = "2.0"
tokio = { version = "1.49", features = ["rt", "sync"] }
tokio-test = "0.4"
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["futures-03"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"
wasm-bindgen-futures = "0.4"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true

[profile.test]
opt-level = 2

[workspace.lints.rust]
unsafe_code = "warn"
# missing_docs = "warn"
rust_2024_compatibility = { level = "warn", priority = -1 }

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
must_use_candidate = "allow"
