[package]
name = "machi-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Derive macros for machi - AI Agent Framework"
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
convert_case.workspace = true
deluxe.workspace = true
indoc.workspace = true
proc-macro2.workspace = true
quote.workspace = true
serde_json.workspace = true
syn.workspace = true

[lints]
workspace = true
